### ISSUE TITLE
Slow loading of the page

### ISSUE THREAD

**Issue by Killian-Zouareg** [LouHent/pride#1]
This tag `<script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=W0OdZt5zyhqawLlUaQeuQ_c04TfBu4DaqqfjOHBfqPRhHDBIu9GaRnqyocTgIMS5t994UYIMp_-QDVQXWCnBsMo-NejAuEGCs9JySjjMwAHXjp4u8vVOyQsfgskxkWy4" charset="UTF-8">` in index.html

 is affecting the loading time of your page by a long shot and seems useless , deleting it will results in your page loading in seconds instead of minutes , tested locally and working : )

**Comment by LouHennenfent** [comment]
I deleted it, it totally works, thanks :)
