### ISSUE TITLE
Site with paywall / loginwall

### ISSUE THREAD

**Issue by Killian-Zouareg** [LouHent/pride#3]
The website for the Saint-Quentin pride requires to login or to pay a subscription to access it's content I propose to use instead 
this link 
(https://12ft.io/proxy?q=http://www.aisnenouvelle.fr/id296842/article/2022-04-12/une-premiere-marche-des-fiertes-en-juin-saint-quentin)
which remove all loginwall/paywall

**Comment by LouHennenfent** [comment]
Thanks, it's done :)
